Проверьте ДЗ
AlexandrLytkin/HomeWork pull request #1
Opened 2022-09-28 11:59 UTC by AlexandrLytkin

2022-09-28 15:48 UTC, OlgaLugacheva requested changes

2022-09-28 15:48 UTC, OlgaLugacheva commented on src/objectAndClass/Book.java
> +    private String nameAuthor;
это поле должно быть типа Author

2022-09-28 15:48 UTC, OlgaLugacheva commented on src/objectAndClass/Book.java
> +    public Book(String bookName, String nameAuthor, int publicationYear) {
параметр конструктора nameAuthor также должен быть типа Author

2022-09-29 10:46 UTC, AlexandrLytkin commented on src/objectAndClass/Book.java
> +    private String nameAuthor;
исправил

2022-09-29 10:47 UTC, AlexandrLytkin commented on src/objectAndClass/Book.java
> +    public Book(String bookName, String nameAuthor, int publicationYear) {
исправил

2022-09-29 10:47 UTC, merged

2022-09-29 17:56 UTC, OlgaLugacheva commented on src/objectAndClass/Book.java
> +    String authorBook;
ранее ты создал класс Author и его и надо использовать вместо String

2022-09-29 17:56 UTC, OlgaLugacheva commented on src/objectAndClass/Book.java
> +        Book book = new Book();
здесь не нужно создавать объект Book, нужно использовать указатель на текущий класс this
т.е. 
this.name  =name;
и т.д.

2022-09-30 13:11 UTC, AlexandrLytkin commented on src/objectAndClass/Book.java
> +        Book book = new Book();
исправил